### ISSUE TITLE
问题：为什么第一个元素的level总是47

### ISSUE THREAD

**Issue by sirodeneko** [huandu/skiplist#13]
level是由randLevel()生成的，但是为什么第一个元素的level总是47（采用最大默认高度的时候）

**Comment by huandu** [comment]
这是一个 bug，第一个元素插入的时候始终使用了 maxLevel - 1 的 level，应该优化一下。我得重新选取一下参数，测试下性能。

**Comment by sirodeneko** [comment]
代码中元素的高度会考虑当前数据的长度，这是否有必要？我认为其并不会带来性能的提升。并且其会破坏高度的随机性，小高度的元素会增多。

**Comment by huandu** [comment]
根据长度定高度是有帮助的，我做过一些定量的测试，前面插入的结点相对较低、后面快速提升 level 的随机范围，这会显著的提升性能，这比纯粹随机要更好。我打算这次做一个更好的算法，加入一些平衡机制来更好的解决生成 level 的问题，不过需要花一些时间。

**Comment by huandu** [comment]
没能找到更好的方案，我观察了各种相关库，也研究了下 level 分布与效率的关系，发现保持平衡的代价过高且收益不明显，所以最终提交了代码移除了各种 randLevel 优化，恢复了最原始的正态分布算法。
