### ISSUE TITLE
请问如何找到大于 score 的第一个 element？

### ISSUE THREAD

**Issue by someblue** [huandu/skiplist#14]
我想实现一个类似于 redis 的 ZRANGEBYSCORE key min max 的功能，找出 score 位于 [min, max] 的 elements，查看 API 文档好像没有找到相关的 API，请问是否有理解错误？

**Comment by huandu** [comment]
暂时没有封装查询类的接口，确实有点不太方便，或许应该封装一下。如果需要查找，假设当前 skip list 是升序排列，那么从 `Front` 开始，从最上面一个 level 开始寻找 `Element` 的 value，找到第一个比 min 小的 level，然后访问 next element 并重复这个过程。

要不我抽空实现一个吧，感觉确实是个缺憾。之前只实现了 kv 访问，并没有实现完整的功能。

**Comment by huandu** [comment]
我在 PR 上进行了 review，非常感谢提交这些代码呀，设计方面的问题我们可在这个 issue 里面讨论~
