### ISSUE TITLE
Is it have a plan to implement safe concurrent read/write on skiplist？

### ISSUE THREAD

**Issue by Jekinnnnnn** [huandu/skiplist#16]
Maybe,repo can provide a option with lock or sync.map mode to implement this feature

**Comment by huandu** [comment]
No plan right now.

It's unlikely to implement a lock-free or element-level-lock skiplist. It means the whole skiplist should be locked for read/write for safety. I'd recommend package users to choose proper locks based on how the skiplist will be visited.
