### ISSUE TITLE
测试发现Key不能够相同

### ISSUE THREAD

**Issue by kong9527** [huandu/skiplist#18]
比如我们指定Key为分数，当相同分数插入的时候会被覆盖

**Comment by huandu** [comment]
对，Key 是唯一的，跟 map 类似。可以通过指定自定义的 `Comparable` 来实现你的需求，甚至模拟 Redis ZSET 的效果，可以参考 [GreaterThanFunc 的例子](https://pkg.go.dev/github.com/huandu/skiplist#example-GreaterThanFunc)。

具体做法：Key 不再是一个简单的数字，而是一个 `struct { Name string; Value int }`，自己实现一个 `Comparable`，仅当 `Name` 相同的时候才算相等，其他时候比较 `Value` 大小来排序。
