### ISSUE TITLE
性能问题!

### ISSUE THREAD

**Issue by 474420502** [huandu/skiplist#5]
这个跳表还有什么优化空间吗, benchmark出来性能比树差2倍以上.

**Comment by huandu** [comment]
@474420502 Show me the benchmark code please. 😄

**Comment by 474420502** [comment]
我自己实现的一个size平衡树, 但是拿avl 加了一个size节点属性, skiplist 1900 ns/op  和 avl 600 - 800 ns/ops 差距也是非常巨大. 等我改完再发吧. 拿gods 的 avl benchmark一下 就行了. 我过几天发给你.

**Comment by huandu** [comment]
嗯，看看代码。每种数据结构都有适应的场景的，并不是说 skiplist 一定在各方面都超越 avl。我当前的实现已经是 Go 所有实现里面性能算是比较好的了，我可以看看你的代码，你的应用场景，思考下有什么优化的空间。

**Comment by huandu** [comment]
这个是当前代码的 benchmark，可以作为参考。

```
$ go version
go version go1.12.1 darwin/amd64
$ go test -bench . -benchmem
goos: darwin
goarch: amd64
pkg: github.com/huandu/skiplist
BenchmarkDefaultWorstInserts-8               	 3000000	       423 ns/op	      91 B/op	       3 allocs/op
BenchmarkDefaultBestInserts-8                	 5000000	       281 ns/op	      91 B/op	       3 allocs/op
BenchmarkWorstInsertsWithLocalRandSource-8   	 5000000	       357 ns/op	      91 B/op	       3 allocs/op
BenchmarkBestInsertsWithLocalRandSource-8    	 5000000	       251 ns/op	      91 B/op	       3 allocs/op
BenchmarkRandomSelect-8                      	 1000000	      1624 ns/op	       8 B/op	       1 allocs/op
PASS
ok  	github.com/huandu/skiplist	9.347s
```

**Comment by 474420502** [comment]
const CompartorSize = 1000000
const NumberMax = 50000000

func TestSave(t *testing.T) {

	f, err := os.OpenFile("../l.log", os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0666)
	if err != nil {
		log.Println(err)
	}
	var l []int
	// for i := 0; len(l) < 1000; i++ {
	// 	v := randomdata.Number(0, 65535)
	// 	l = append(l, v)
	// }

	//m := make(map[int]int)
	for i := 0; len(l) < CompartorSize; i++ {
		v := randomdata.Number(0, NumberMax)
		// if _, ok := m[v]; !ok {
		// 	m[v] = v
		l = append(l, v)
		// }
	}

	var result bytes.Buffer
	encoder := gob.NewEncoder(&result)
	encoder.Encode(l)
	lbytes := result.Bytes()
	f.Write(lbytes)

}

func loadTestData() []int {
	data, err := ioutil.ReadFile("../l.log")
	if err != nil {
		log.Println(err)
	}
	var l []int
	decoder := gob.NewDecoder(bytes.NewReader(data))
	decoder.Decode(&l)
	return l
}

func BenchmarkSkipListSet(b *testing.B) {

	l := loadTestData()

	execCount := 50
	b.N = len(l) * execCount

	for i := 0; i < execCount; i++ {
		sl := skiplist.New(skiplist.Int)
		for _, v := range l {
			sl.Set(v, v)
		}
}

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkSkipListSet)$ ./

goos: linux
goarch: amd64
BenchmarkSkipListSet-8   	50000000	      2300 ns/op	      90 B/op	       3 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	115.027s
Success: Benchmarks passed.


func BenchmarkPut(b *testing.B) {
	l := loadTestData()

	b.ResetTimer()
	b.StartTimer()

	execCount := 50
	b.N = len(l) * execCount
	for i := 0; i < execCount; i++ {
		tree := New(utils.IntComparator)
		for _, v := range l {
			tree.Put(v)
		}
	}
}

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkPut)$ ./

goos: linux
goarch: amd64
BenchmarkPut-8   	50000000	       871 ns/op	      56 B/op	       2 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	43.626s
Success: Benchmarks passed.

测试过了无论多少都是这个差距,  如果带key的tree的, 就 950ns/op 左右.

**Comment by 474420502** [comment]
他们测试的数据也是随机生成的, 但是保证了大家都是用相同数据, 并且顺序也一致. @huandu

**Comment by 474420502** [comment]
const CompartorSize = 10000
const NumberMax = 50000000

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkPut)$ ./

goos: linux
goarch: amd64
BenchmarkPut-8   	  500000	       212 ns/op	      56 B/op	       2 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	1.446s
Success: Benchmarks passed.

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkSkipListSet)$ ./

goos: linux
goarch: amd64
BenchmarkSkipListSet-8   	  500000	       403 ns/op	      91 B/op	       4 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	3.101s
Success: Benchmarks passed.

**Comment by 474420502** [comment]
越小差距就越不明显了 . 
const CompartorSize = 100
const NumberMax = 50000000

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkSkipListSet)$ ./

goos: linux
goarch: amd64
BenchmarkSkipListSet-8   	    5000	       285 ns/op	      99 B/op	       4 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	0.028s
Success: Benchmarks passed.

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkPut)$ ./

goos: linux
goarch: amd64
BenchmarkPut-8   	    5000	        97.5 ns/op	      56 B/op	       2 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	0.014s
Success: Benchmarks passed.

**Comment by 474420502** [comment]
我实现一个sbt以后拿来对比吧, 我的树还差个Range接口, 最近工作忙, 后面我开源出来.

**Comment by 474420502** [comment]
我想确认对比skiplist的真实性能达到什么程度. 按照它的结构, 肯定没树的效率高, 这个是我认为的, 验证一下.

**Comment by 474420502** [comment]
我测试过skiplist rank get 各个方面都不如树的高. 等我有时间才发个完整的出来.

**Comment by huandu** [comment]
Skiplist 的优势是在于 key 很多的时候 Get/Set 效率高于二叉树，拥有接近常数的效率。这是因为 skiplist 的理论复杂度是 O(log_level(N))，按照默认 level = 32 来看，当 N > 2^20 的时候，理论上 skiplist Get/Set 平均 4 次查询，而二叉树平均得 20 次了。

不过 skiplist 非常依赖于随机数的均衡性，当前这方面其实没有做特殊优化，如果要做的更好的话理论上应该根据 key 的值和分布情况来确定 rand 算法才行。

**Comment by 474420502** [comment]
我觉得不对的, 100万对比出来也是树优势大, skiplist还要找到key后 再向前. 再level判断的指令. 那些虽然我知道大概原理. 实测都是树优势大, 或者你给个最优的随机代码给我, 对比下.

**Comment by huandu** [comment]
所以还是 show me the benchmark code，我来看看实测情况如何吧，我无法通过 case 来说明好坏，没有一个基准。

**Comment by 474420502** [comment]
上面就是测试 benchmark code

**Comment by 474420502** [comment]
sl := skiplist.New(skiplist.Int)
	for i := 0; i < b.N; i++ {
		sl.Set(i, i)
	}
Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkSkipListSet)$ ./

goos: linux
goarch: amd64
BenchmarkSkipListSet-8   	 5000000	       349 ns/op	      91 B/op	       4 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	2.117s
Success: Benchmarks passed.

	tree := New(utils.IntComparator)
	for i := 0; i < b.N; i++ {
		tree.Put(i)
	}

Running tool: /usr/local/share/go/bin/go test -benchmem -run=^$ -bench ^(BenchmarkSkipListSet)$ ./

goos: linux
goarch: amd64
BenchmarkSkipListSet-8   	10000000	       263 ns/op	      56 B/op	       1 allocs/op
PASS
ok  	_/home/eson/test/structure/avlindex	2.897s
Success: Benchmarks passed.

**Comment by 474420502** [comment]
等一段时间我测试稳定了,   再给你看这些测试, 包括所有源代码.

**Comment by huandu** [comment]
好，等你的代码。主要不是在于我不知道怎么写针对 skiplist 的 benchmark，而是不知道 avl tree 代码长什么样，不知道哪些地方我应该对照的作出修改。

有一个细节需要提醒你一下，默认的 skiplist rand source 是 `math/rand` 的默认 rand source，这个是有全局 mutex 的，会损失一点性能。

**Comment by 474420502** [comment]
@huandu 
https://github.com/474420502/focus
readme 有个例子, 对标的SkipList.
那个Mutex我觉得不是那个会导致性能损失的原因. 
几乎忘记了, 最近很忙. 在搞其他语言比较多.

**Comment by huandu** [comment]
看起来代码写的不错呀，我周末跑跑看一下

**Comment by huandu** [comment]
```
BenchmarkSideBySidePQKDefaultWorstInserts-12                    20000000               317 ns/op              80 B/op          2 allocs/op
BenchmarkSideBySideDefaultWorstInserts-12                       30000000               327 ns/op              91 B/op          4 allocs/op

BenchmarkSideBySidePQKDefaultBestInserts-12                     30000000               230 ns/op              91 B/op          3 allocs/op
BenchmarkSideBySideDefaultBestInserts-12                        30000000               210 ns/op              91 B/op          3 allocs/op

BenchmarkSideBySidePQKWorstInsertsWithLocalRandSource-12        30000000               297 ns/op              80 B/op          2 allocs/op
BenchmarkSideBySideWorstInsertsWithLocalRandSource-12           30000000               315 ns/op              91 B/op          3 allocs/op

BenchmarkSideBySidePQKBestInsertsWithLocalRandSource-12         30000000               296 ns/op              80 B/op          2 allocs/op
BenchmarkSideBySideBestInsertsWithLocalRandSource-12            30000000               198 ns/op              91 B/op          3 allocs/op

BenchmarkSideBySidePQKRandomSelect-12                            5000000              1947 ns/op               8 B/op          1 allocs/op
BenchmarkSideBySideRandomSelect-12                               5000000              2647 ns/op               8 B/op          1 allocs/op
```

跑了一下 benchmark，确实慢了一些，我看着觉得是内存分配和计算复杂度（算了 rand）。

**Comment by 474420502** [comment]
https://github.com/474420502/structure_benckmark
@huandu  这个是我之前测的.

**Comment by 474420502** [comment]
@huandu  你的测试肯定是去重key了, 而我写的不去重的. 去重的数据(总的量会少, 已测, 有不去重的版本)会快数倍多, 意味着更快. 但是我目的是做队列.并且有index 功能. skiplist 优势只在并行处理. 但是非常复杂. 我觉得非常慢.

**Comment by 474420502** [comment]
我已经有结论了, 事实上很多人没理解. 链表不可能比上用size平衡的树(原理上). 只不过skiplist可以比较好并行处理.. 我看了很多写skiplist的人结论, 很多人并不理解性能. 所有大量情景的测试都试过了,性能上并没优势. size平衡的树也可以处理成并行的处理方式可能会复杂一点. 以后写一个类型rocksdb. skiplist的处理串行compact的方式试下性能. 非常感谢解答.

**Comment by 474420502** [comment]
https://github.com/474420502/priority_queue_test 再给个c/c++测试.
