### ISSUE TITLE
exceed capacity need delete 

### ISSUE THREAD

**Issue by zjh-codeset** [huandu/skiplist#7]
add Back(Front) DelFront DelBack  Function

**Comment by huandu** [comment]
Working on it.

**Comment by zjh-tech** [comment]
help me delete issues ,my github has your project

**Comment by huandu** [comment]
It was implemented by 334956e. There are new methods [List#RemoveBack](https://pkg.go.dev/github.com/huandu/skiplist#SkipList.RemoveBack), [List#RemoveElement](https://pkg.go.dev/github.com/huandu/skiplist#SkipList.RemoveElement) and [List#RemoveFront](https://pkg.go.dev/github.com/huandu/skiplist#SkipList.RemoveFront) to enable you to delete any element.

**Comment by zjh-tech** [comment]
show your project in my github  , need delete I say issues in your github project , my github donot show your project after  delete ,thank you !!!

**Comment by huandu** [comment]
I don't get your point. Can you please let me know what's your requirement more clearly?

或者用中文说一下，没必要勉强用英文。 😉

**Comment by zjh-tech** [comment]
帮忙把我的问题删除下，不然我的github工程里面一直有你的工程问题提示，看上去不舒服
